deployment:
  tasks:
    - export GITPATH=/home/techpsjornada/repositories/dev_techps/armazem_paraiba/*
    - export DEPLOYPATH=/home/techpsjornada/public_html/dev/armazem_paraiba/
    - /bin/cp -R $GITPATH $DEPLOYPATH
