# This is the main deployment section
deployment:
  tasks:
   - export  GIT_REPO_PATH=/home/techpsjornada/repositories/dev_techps/armazem_paraiba/*
   - export DEPLOY_DEV_PATH=/home/techpsjornada/public_html/dev/armazem_paraiba/
   - /bin/cp -R $GITPATH $DEPLOYPATH
