---
deployment:
  tasks:
    - export DEPLOYPATH="/home/brasomo/public_html"
    - /bin/cp .gitignore "$DEPLOYPATH"
    - /bin/cp htaccess "$DEPLOYPATH"
    - /bin/cp index2.php "$DEPLOYPATH"
    - /bin/cp recupera_senha.php "$DEPLOYPATH"
    - /bin/cp Temos_de_uso.html "$DEPLOYPATH"
    - /bin/cp version.php "$DEPLOYPATH"
    - /bin/cp -r PHPMailer "$DEPLOYPATH"
    - /bin/cp -r contex20 "$DEPLOYPATH"
    - /bin/cp -r armazem_paraiba "$DEPLOYPATH"
