# This is the main deployment section
deployment:
  tasks:
    - name: Run tests  # Task to run all tests before deployment
      command: |
        # TODO fazer testes
        echo 'ok'

    - name: Deploy application  # Task to deploy the application
      command: |
        GIT_REPO_PATH="/home/techpsjornada/repositories/dev_techps/*"
        DEPLOY_DEV_PATH="/home/techpsjornada/public_html/dev/armazem_paraiba/"
        # Copy files to dev path
        /bin/cp -R $GITPATH $DEPLOYPATH
