deployment:
  tasks:
    - export GENERAL=/home/techpsjornada/repositories/gestaodeponto/*
    - export DOMAIN=/home/techpsjornada/repositories/gestaodeponto/armazem_paraiba/*

    - export GENERALDEPLOY=/home/techpsjornada/public_html/gestaodeponto
    - export BRASO=/home/techpsjornada/public_html/gestaodeponto/braso
    - export CARAU=/home/techpsjornada/public_html/gestaodeponto/carau_transporte
    - export COMAV=/home/techpsjornada/public_html/gestaodeponto/comav
    - export FEIJAO=/home/techpsjornada/public_html/gestaodeponto/feijao_turqueza
    - export FS_LOG=/home/techpsjornada/public_html/gestaodeponto/fs_log_transportes
    - export LOGSYNC=/home/techpsjornada/public_html/gestaodeponto/logsync_techps
    - export OPAFRUTAS=/home/techpsjornada/public_html/gestaodeponto/opafrutas
    - export PKF=/home/techpsjornada/public_html/gestaodeponto/pkf_medeiros
    - export QUALY=/home/techpsjornada/public_html/gestaodeponto/qualy_transportes
    - export TECHPS=/home/techpsjornada/public_html/gestaodeponto/techps
    - export TRAMPGAS=/home/techpsjornada/public_html/gestaodeponto/trampolim_gas
    - export NH_TRANSP=/home/techpsjornada/public_html/gestaodeponto/nh_transportes
    - export JRJ_ORG=/home/techpsjornada/public_html/gestaodeponto/jrj_organizacao
    - export HN_TRANSP=/home/techpsjornada/public_html/gestaodeponto/hn_transportes


    - /bin/cp -R $GENERAL $GENERALDEPLOY
    
    - /bin/cp -R $DOMAIN $BRASO
    - /bin/cp -R $DOMAIN $CARAU
    - /bin/cp -R $DOMAIN $COMAV
    - /bin/cp -R $DOMAIN $FEIJAO
    - /bin/cp -R $DOMAIN $FS_LOG
    - /bin/cp -R $DOMAIN $LOGSYNC
    - /bin/cp -R $DOMAIN $OPAFRUTAS
    - /bin/cp -R $DOMAIN $PKF
    - /bin/cp -R $DOMAIN $QUALY
    - /bin/cp -R $DOMAIN $TECHPS
    - /bin/cp -R $DOMAIN $TRAMPGAS
    - /bin/cp -R $DOMAIN $NH_TRANSP
    - /bin/cp -R $DOMAIN $JRJ_ORG
    - /bin/cp -R $DOMAIN $HN_TRANSP
