deployment:
  tasks:
    - export GENERAL=/home/devtechpsgj/repositories/dev_techps/*
    - export DOMAIN=/home/devtechpsgj/repositories/dev_techps/armazem_paraiba/*
    - export GENERALDEPLOY=/home/devtechpsgj/public_html/dev

    - export IFRN=/home/devtechpsgj/public_html/dev/ifrn
    - export LEMON=/home/devtechpsgj/public_html/dev/lemon
    - export NH_TRANSPORTES=/home/devtechpsgj/public_html/dev/nh_transportes
    - export OPAFRUTAS=/home/devtechpsgj/public_html/dev/opafrutas
    - export TRANSCOPEL=/home/devtechpsgj/public_html/dev/transcopel
    
    - /bin/cp -R $GENERAL $GENERALDEPLOY

    - /bin/cp -R $DOMAIN $IFRN
    - /bin/cp -R $DOMAIN $LEMON
    - /bin/cp -R $DOMAIN $NH_TRANSPORTES
    - /bin/cp -R $DOMAIN $OPAFRUTAS
    - /bin/cp -R $DOMAIN $TRANSCOPEL
