deployment:
  tasks:
    - export GENERAL=/home/techpsjornada/repositories/dev_techps/*
    - export DOMAIN=/home/techpsjornada/repositories/dev_techps/armazem_paraiba/*
    - export GENERALDEPLOY=/home/techpsjornada/public_html/dev

    - export OPAFRUTAS=/home/techpsjornada/public_html/dev/opafrutas
    
    - /bin/cp -R $GENERAL $GENERALDEPLOY

    - /bin/cp -R $DOMAIN $OPAFRUTAS