deployment:
  tasks:
    - export GENERAL=/home/tech1694/repositories/prod/*
    - export DOMAIN=/home/tech1694/repositories/prod/armazem_paraiba/*





    - export GENERALDEPLOY=/home/tech1694/public_html/dev/
    - export BLUEROAD=/home/tech1694/public_html/dev/blueroad
    - export BRASO=/home/tech1694/public_html/dev/braso
    - export CARAU=/home/tech1694/public_html/dev/carau_transporte
    - export COMAV=/home/tech1694/public_html/dev/comav
    - export FEIJAO=/home/tech1694/public_html/dev/feijao_turqueza
    - export FS_LOG=/home/tech1694/public_html/dev/fs_log_transportes
    - export HN_TRANSP=/home/tech1694/public_html/dev/hn_transportes
    - export IFRN=/home/tech1694/public_html/dev/ifrn
    - export JRJ_ORG=/home/tech1694/public_html/dev/jrj_organizacao
    - export LOGSYNC=/home/tech1694/public_html/dev/logsync_techps
    - export LEMON=/home/tech1694/public_html/dev/lemon
    - export NH_TRANSP=/home/tech1694/public_html/dev/nh_transportes
    - export OPAFRUTAS=/home/tech1694/public_html/dev/opafrutas
    - export PKF=/home/tech1694/public_html/dev/pkf_medeiros
    - export QUALY=/home/tech1694/public_html/dev/qualy_transportes
    - export TECHPS=/home/tech1694/public_html/dev/techps
    - export TECHPSDEMO=/home/tech1694/public_html/dev/techps_demo
    - export TRAMPGAS=/home/tech1694/public_html/dev/trampolim_gas
    - export TRANSCOPEL=/home/tech1694/public_html/dev/transcopel
    - export SAO_LUCAS=/home/tech1694/public_html/dev/sao_lucas
    - export PB_TRANSPORTES=/home/tech1694/public_html/dev/pb_transportes
    - export ODONTOTANGARA=/home/tech1694/public_html/dev/odontotangara
    - export CLINICA_GERLANE=/home/tech1694/public_html/dev/clinica_gerlane
    - export IRANEIDE_OLIVEIRA=/home/tech1694/public_html/dev/iraneide_oliveira
    - export MIDIA_DIGITAL=/home/tech1694/public_html/dev/midia_digital
    - export ENOVE=/home/tech1694/public_html/dev/enove
    - export ENOVE=/home/tech1694/public_html/dev/t_militao





    - /bin/cp -R $GENERAL $GENERALDEPLOY
    
    - /bin/cp -R $DOMAIN $BRASO
    - /bin/cp -R $DOMAIN $CARAU
    - /bin/cp -R $DOMAIN $COMAV
    - /bin/cp -R $DOMAIN $FEIJAO
    - /bin/cp -R $DOMAIN $FS_LOG
    - /bin/cp -R $DOMAIN $HN_TRANSP
    - /bin/cp -R $DOMAIN $IFRN
    - /bin/cp -R $DOMAIN $JRJ_ORG
    - /bin/cp -R $DOMAIN $LEMON
    - /bin/cp -R $DOMAIN $LOGSYNC
    - /bin/cp -R $DOMAIN $NH_TRANSP
    - /bin/cp -R $DOMAIN $OPAFRUTAS
    - /bin/cp -R $DOMAIN $PKF
    - /bin/cp -R $DOMAIN $QUALY
    - /bin/cp -R $DOMAIN $TECHPS
    - /bin/cp -R $DOMAIN $TECHPSDEMO
    - /bin/cp -R $DOMAIN $TRAMPGAS
    - /bin/cp -R $DOMAIN $TRANSCOPEL
    - /bin/cp -R $DOMAIN $BLUEROAD
    - /bin/cp -R $DOMAIN $SAO_LUCAS
    - /bin/cp -R $DOMAIN $PB_TRANSPORTES
    - /bin/cp -R $DOMAIN $ODONTOTANGARA
    - /bin/cp -R $DOMAIN $CLINICA_GERLANE
    - /bin/cp -R $DOMAIN $IRANEIDE_OLIVEIRA
    - /bin/cp -R $DOMAIN $MIDIA_DIGITAL
    - /bin/cp -R $DOMAIN $ENOVE
    - /bin/cp -R $DOMAIN $T_MILITAO
