deployment:
  tasks:
    # Diret贸rios gerais
    - export GENERAL=/home/devtechpsgj/repositories/dev_techps/*
    - export DOMAIN=/home/devtechpsgj/repositories/dev_techps/armazem_paraiba/*
    - export GENERALDEPLOY=/home/devtechpsgj/public_html/dev

    # Diret贸rios espec铆ficos de cada projeto
    
    - export IFRN=/home/devtechpsgj/public_html/dev/ifrn
    - export OPAFRUTAS=/home/devtechpsgj/public_html/dev/opafrutas
    - export ARMAZEMPARAIBA=/home/devtechpsgj/public_html/dev/armazem_paraiba
    - export BLUEROAD=/home/devtechpsgj/public_html/dev/blueroad
    - export SAOLUCAS=/home/devtechpsgj/public_html/dev/sao_lucas


    # Copiando diret贸rios
    - /bin/cp -R $GENERAL $GENERALDEPLOY
    - /bin/cp -R $DOMAIN $IFRN
    - /bin/cp -R $DOMAIN $OPAFRUTAS
    - /bin/cp -R $DOMAIN $ARMAZEMPARAIBA
    - /bin/cp -R $DOMAIN $BLUEROAD
    - /bin/cp -R $DOMAIN $SAOLUCAS

