version: '2.2'

services:
  db:
    image: mariadb:10.5
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: techpsjornada_dev
    ports:
      - "3306:3306"

  apache:
    build:
      context: .
      dockerfile: Dockerfile.win8
    container_name: dev_techps_apache
    volumes:
      - .:/var/www/html/braso
    ports:
      - "80:8080"
    links:
      - db

  adminer:
    image: adminer
    environment:
      UPLOAD: 4096M
    ports:
      - "8000:8080"
    links:
      - db