services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE:  armazem

  apache:
    image: php:7.4-apache
    container_name: dev_techps_apache

  adminer:
    image: adminer
    volumes:
        - .:/var/www/html/braso/
    environment:
      UPLOAD: 4096M
    ports:
      - 8000:8080
