services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE:  armazem

  adminer:
    image: adminer
    volumes:
        - .:/var/www/html/braso/
    environment:
      UPLOAD: 4096M
    ports:
      - 8000:8080
