# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: bitnami/git

pipelines:
  branches:
    master:
    - step:
        name: Deploy production
        deployment: production
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://modulusistemas.com.br/public_html/contex20
