name: Executar Testes do Insomnia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-insomnia-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # ou sua versão específica do PHP

    - name: Instalar dependências
      run: composer install --no-progress --prefer-dist

    - name: Executar Testes PHP Unit
      run: vendor/bin/phpunit

    - name: Instalar Newman CLI
      run: npm install -g newman

    - name: Executar Testes do Insomnia
      run: |
        newman run tests/insomnia.json
